"""
train_model.py
Trains the MicroLend XGBoost model on msme_loans.csv (a synthetic dataset,
generated by an AI tool — NOT real bank/Lending Club data; be upfront about
that if asked) and saves it to model/microlend_model.pkl.

Run this once before starting the API:
    python train_model.py

Make sure msme_loans.csv is in the same folder as this script.
"""

import os
import csv
import numpy as np
import joblib
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score

CSV_PATH = os.path.join(os.path.dirname(__file__), "msme_loans.csv")

# Only the 8 features the live form actually collects — the dataset has a
# few extra engineered columns (monthly_upi, has_digital_payment,
# tenure_score) that we can't use without adding new fields to the form.
FEATURE_COLS = [
    "business_age_years", "daily_upi_sales", "utility_bill_score",
    "supplier_repay_score", "loan_to_revenue_ratio", "biz_type_encoded",
    "city_tier", "purpose_encoded",
]
LABEL_COL = "repaid_on_time"

with open(CSV_PATH, newline="") as f:
    reader = csv.DictReader(f)
    rows = list(reader)

X = np.array([[float(row[c]) for c in FEATURE_COLS] for row in rows])
y = np.array([float(row[LABEL_COL]) for row in rows])

print(f"Loaded {len(rows)} rows from {CSV_PATH}")
print(f"Label balance (repaid_on_time=1): {y.mean():.3f}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.85,
    colsample_bytree=0.85,
    eval_metric="logloss",
    random_state=42,
)
model.fit(X_train, y_train)

pred_proba = model.predict_proba(X_test)[:, 1]
pred_label = (pred_proba >= 0.5).astype(int)
auc = roc_auc_score(y_test, pred_proba)
acc = accuracy_score(y_test, pred_label)

print(f"Validation AUC-ROC : {auc:.3f}")
print(f"Validation Accuracy: {acc:.3f}")

out_dir = os.path.join(os.path.dirname(__file__), "model")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "microlend_model.pkl")
joblib.dump(model, out_path)
print(f"Model saved to {out_path}")
